import { useState, useEffect } from 'react';
import { getWaitlistEntries, isSupabaseConfigured } from '../lib/supabase';
import { WaitlistEntry } from '../types';
import { Database, ShieldAlert, Sparkles, Trash2, ListFilter, Clipboard, CheckCircle, PlusCircle } from 'lucide-react';

export default function AdminPortal() {
  const [entries, setEntries] = useState<WaitlistEntry[]>([]);
  const [source, setSource] = useState<'supabase' | 'localStorage'>('localStorage');
  const [errorStr, setErrorStr] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [copiedSql, setCopiedSql] = useState(false);

  const fetchLogs = async () => {
    setLoading(true);
    try {
      const res = await getWaitlistEntries();
      setEntries(res.data);
      setSource(res.source);
      setErrorStr(res.error);
    } catch (e: any) {
      setErrorStr(e.message || 'Error occurred');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchLogs();
  }, []);

  const handleInjectSamples = () => {
    const sampleEntries: WaitlistEntry[] = [
      {
        id: 'sample-1',
        email: 'alpha_shredder@calnic.fit',
        workoutPreference: 'Muscle Up Mastery',
        experienceLevel: 'Athletic Control',
        createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
        customAvatarSeed: 4
      },
      {
        id: 'sample-2',
        email: 'beast_mode8@gmail.com',
        workoutPreference: 'Upper Body Power',
        experienceLevel: 'Intermediate',
        createdAt: new Date(Date.now() - 360000 * 24).toISOString(),
        customAvatarSeed: 12
      },
      {
        id: 'sample-3',
        email: 'yoga_crossfit_dude@outlook.com',
        workoutPreference: 'Core Shred & L-Sit',
        experienceLevel: 'Beginner',
        createdAt: new Date(Date.now() - 36000 * 12).toISOString(),
        customAvatarSeed: 78
      }
    ];

    const existingLocal = localStorage.getItem('calnic_waitlist');
    const existing: WaitlistEntry[] = existingLocal ? JSON.parse(existingLocal) : [];
    
    // Merge only unique
    const filteredSamples = sampleEntries.filter(s => !existing.some(e => e.email === s.email));
    const merged = [...filteredSamples, ...existing];
    localStorage.setItem('calnic_waitlist', JSON.stringify(merged));
    fetchLogs();
  };

  const handleClearBackup = () => {
    if (confirm("Are you sure you want to delete all local waitlist backups?")) {
      localStorage.removeItem('calnic_waitlist');
      fetchLogs();
    }
  };

  const sqlSnippet = `-- 🚀 COPY & PASTE PASTE DIRECTLY IN YOUR SUPABASE SQL EDITOR

CREATE TABLE calnic_waitlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  workout_preference TEXT DEFAULT 'Upper Body Power',
  experience_level TEXT DEFAULT 'Beginner',
  avatar_seed INT DEFAULT 20,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable select permissions for public anonymous roles
ALTER TABLE calnic_waitlist ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anonymous read" ON calnic_waitlist FOR SELECT TO anon USING (true);
CREATE POLICY "Allow public insert" ON calnic_waitlist FOR INSERT TO anon WITH CHECK (true);
`;

  const copySql = () => {
    navigator.clipboard.writeText(sqlSnippet);
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 2000);
  };

  return (
    <section id="developer-admin-portal" className="bg-neutral-950 border border-neutral-900 rounded-3xl p-6 relative overflow-hidden text-neutral-200">
      
      {/* Background Tech Net Grid */}
      <div className="absolute top-0 right-0 w-32 h-32 bg-amber-500/5 rounded-full blur-2xl pointer-events-none" />
      
      {/* Header Info */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6 pb-6 border-b border-neutral-900">
        <div>
          <div className="flex items-center space-x-2.5">
            <span className="w-7.5 h-7.5 rounded-lg bg-red-600/10 border border-red-500/20 flex items-center justify-center text-red-500">
              <Database className="w-4 h-4" />
            </span>
            <h3 className="text-lg font-black tracking-wide uppercase">CALNIC DEV PORTAL</h3>
          </div>
          <p className="text-xs text-neutral-400 mt-1 max-w-xl">
            Audit database connections, check local submissions, and copy schemas to configure complete cloud deployments.
          </p>
        </div>

        <div className="flex items-center gap-2">
          {isSupabaseConfigured ? (
            <span className="text-[10px] font-mono font-bold bg-green-950/80 border border-green-850 text-green-400 px-3 py-1.5 rounded-full flex items-center gap-1.5">
              <span className="w-1.5 h-1.5 rounded-full bg-green-500 animate-[pulse_1s_infinite]" />
              SUPABASE CLOUD ACTIVE
            </span>
          ) : (
            <span className="text-[10px] font-mono font-bold bg-neutral-900 border border-neutral-800 text-neutral-400 px-3 py-1.5 rounded-full flex items-center gap-1.5">
              <span className="w-1.5 h-1.5 rounded-full bg-neutral-500" />
              LOCAL DEV SANDBOX fallback
            </span>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        
        {/* Left Side: table of logs */}
        <div className="lg:col-span-7 space-y-4">
          <div className="flex justify-between items-center bg-neutral-900/40 p-3 rounded-xl border border-neutral-800/80">
            <span className="text-xs font-bold text-neutral-300 flex items-center gap-1.5">
              <ListFilter className="w-4 h-4" /> Signups Register ({entries.length})
            </span>

            <div className="flex items-center space-x-1.5">
              <button
                onClick={handleInjectSamples}
                className="text-[10px] font-mono font-bold px-2.5 py-1 bg-red-600/10 hover:bg-red-600/20 text-red-400 border border-red-500/10 rounded-lg transition flex items-center gap-1"
                title="Populate immediate placeholder emails for UI inspection."
              >
                <PlusCircle className="w-3.5 h-3.5" /> Inject Samples
              </button>
              <button
                onClick={handleClearBackup}
                className="text-[10px] font-mono font-bold px-2.5 py-1 bg-neutral-900 hover:bg-red-950/20 text-neutral-500 hover:text-red-400 border border-neutral-800 rounded-lg transition flex items-center gap-1"
                title="Delete all stored inputs from LocalStorage."
              >
                <Trash2 className="w-3.5 h-3.5" /> Reset Local
              </button>
            </div>
          </div>

          {errorStr && (
            <div className="p-3 bg-amber-950/20 border border-amber-900/30 rounded-xl flex items-start gap-2.5 text-neutral-300">
              <ShieldAlert className="w-5 h-5 text-amber-500 flex-shrink-0 mt-0.5" />
              <div>
                <span className="text-xs font-bold text-amber-400">Database Message Log:</span>
                <p className="text-[10.5px] font-mono mt-0.5 leading-relaxed text-amber-500/95">{errorStr}</p>
              </div>
            </div>
          )}

          {/* Table list */}
          <div className="bg-neutral-950 border border-neutral-900 rounded-xl overflow-hidden max-h-76 overflow-y-auto custom-scrollbar">
            {entries.length === 0 ? (
              <div className="py-12 text-center">
                <p className="text-xs text-neutral-500 font-mono">No registered entries detected in current database.</p>
                <button 
                  onClick={handleInjectSamples} 
                  className="mt-3 text-[11px] text-red-500 hover:underline font-bold"
                >
                  Inject mock rows to preview styling density →
                </button>
              </div>
            ) : (
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-neutral-900/60 text-[9px] font-mono text-neutral-500 border-b border-neutral-800">
                    <th className="py-2.5 px-4 font-semibold uppercase">Warrior Account</th>
                    <th className="py-2.5 px-4 font-semibold uppercase">Focus Target</th>
                    <th className="py-2.5 px-4 font-semibold uppercase">Skill level</th>
                    <th className="py-2.5 px-4 font-semibold uppercase text-right">Signed Up</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-neutral-900 text-xs font-sans">
                  {entries.map((item) => (
                    <tr key={item.id} className="hover:bg-neutral-900/30 transition">
                      <td className="py-3 px-4 font-mono text-neutral-200 truncate max-w-44 select-all" title={item.email}>
                        {item.email}
                      </td>
                      <td className="py-3 px-4">
                        <span className="px-2 py-0.5 rounded-sm text-[10px] font-medium bg-neutral-900 text-neutral-300 border border-neutral-800/80">
                          {item.workoutPreference}
                        </span>
                      </td>
                      <td className="py-3 px-4 font-semibold text-red-500">
                        {item.experienceLevel}
                      </td>
                      <td className="py-3 px-4 text-right text-[10px] font-mono text-neutral-500">
                        {new Date(item.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>

        {/* Right Side: database configurations with code copies */}
        <div className="lg:col-span-5 space-y-4">
          <div className="bg-neutral-900/40 p-4.5 rounded-2xl border border-neutral-900 relative">
            <span className="text-xs font-bold text-neutral-200 uppercase tracking-wide block mb-1">
              Supabase Postgres SQL Schema
            </span>
            <p className="text-[10.5px] text-neutral-400 mb-3 leading-relaxed">
              If deploying to live servers, execute the query below on your Supabase Console to mount the exact schema.
            </p>

            <div className="relative">
              <pre className="p-3 bg-black rounded-xl text-[10px] font-mono text-green-500 h-44 overflow-y-auto border border-neutral-800 custom-scrollbar select-all leading-relaxed whitespace-pre">
                {sqlSnippet}
              </pre>
              
              <button
                onClick={copySql}
                className="absolute right-3.5 top-3.5 px-2.5 py-1.5 bg-neutral-900 border border-neutral-800 hover:text-white rounded-lg text-neutral-400 text-[10px] font-mono font-bold transition flex items-center gap-1 active:scale-95"
              >
                {copiedSql ? (
                  <>
                    <CheckCircle className="w-3.5 h-3.5 text-green-500" /> COPIED!
                  </>
                ) : (
                  <>
                    <Clipboard className="w-3.5 h-3.5" /> COPY SQL
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
        
      </div>

    </section>
  );
}
